
language: cpp

env:
  global:
  - ExternalData_OBJECT_STORES="${HOME}/.ExternalData"
  - PROJ_SRC="${TRAVIS_BUILD_DIR}"
  - ITK_REPOSITORY_REMOTE="https://ITK.org/ITK.git"
  - ITK_REPOSITORY="${ExternalData_OBJECT_STORES}/ITK.git"
  - ITK_MODULE_NAME=ExternalTemplate
  - ITK_TAG=master
  - ITK_SRC="${HOME}/ITK"

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja $( command -V cmake &>2 /dev/null || echo "cmake" ); fi

before_script:
   - cmake --version
   - env
   - ( cd ${ExternalData_OBJECT_STORES} && if [[ ! -e ${ITK_REPOSITORY} ]]; then git clone --mirror ${ITK_REPOSITORY_REMOTE}; fi && cd ${ITK_REPOSITORY} && git remote update )
   - git clone --single-branch ${ITK_REPOSITORY} -b "${ITK_TAG}" "${ITK_SRC}" && ( cd ${ITK_SRC}/Modules/Remote && ln -s ${PROJ_SRC} ${ITK_MODULE_NAME} )
   - ( cd ${PROJ_SRC}/test && git clone --single-branch ${ITK_REPOSITORY} -b dashboard dashboard)

script:
   - ctest -V -S ${PROJ_SRC}/test/ci/dashboard.cmake
